package org.summo.blog.verticality;

public final class Constants {

    private Constants() {
    }

    public static final String LOGTAG = "Verticality";

    public static final String LOREM_IPSUM[] = new String[] {
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In quis odio id ipsum lacinia varius ac id metus. Nam eget ipsum vitae sapien aliquam interdum. In hac habitasse platea dictumst. Sed faucibus ultricies tempor. Aliquam aliquam viverra metus, eget aliquet eros blandit ut. Etiam justo libero, faucibus id gravida adipiscing, facilisis in mi. Pellentesque ullamcorper, odio a blandit fringilla, velit ipsum aliquam nisl, nec feugiat eros sem in lectus.",

        "Aliquam ut sem felis. In pulvinar augue ac enim lobortis in feugiat mauris vulputate. Morbi at magna odio, eget volutpat lacus. Duis enim tortor, vulputate nec sodales et, porta auctorodio. Nam sit amet orci sed eros tincidunt euismod sit amet in erat. Praesent eget magna a urna dapibus semper. In ornare enim quis lectus suscipit condimentum.",

        "Sed erat quam, adipiscing et egestas molestie, fermentum id urna. Nam vestibulum, velit ac commodo laoreet, nibh mauris ullamcorper nunc, id blandit sapien velit ullamcorper massa. Mauris dui tortor, iaculis fermentum placerat at, pellentesque a nisl. Vestibulum pretium felis vitae nunc commodo convallis. Donec ac augue eget quam laoreet ultrices. Sed nisi augue, pulvinar vel condimentum ac, iaculis non massa. Integer pulvinar varius sem a molestie. Sed ante ante, condimentum non tempus sit amet, eleifend at massa. Phasellus et libero nunc. Nunc dolor magna, varius eu pretium non, blandit rhoncus arcu. Vivamus at ligula sit amet tortor consectetur egestas vitae non velit. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Praesent est diam, faucibus vitae tristique id, pharetra non velit. Nulla ut ultrices felis. Cras hendrerit turpis non leo ultrices sit amet venenatis enim placerat.",

        "Mauris enim ante, venenatis vel interdum a, commodo et lacus. Curabitur nulla urna, egestas id venenatis quis, iaculis ut erat. Etiam vulputate mauris sit amet lectus malesuada adipiscing. Vivamus iaculis malesuada suscipit. Ut tempor nibh eu lacus pellentesque commodo lacinia lorem pretium. Proin venenatis odio vel purus congue nec imperdiet odio volutpat. Aenean porttitor feugiat facilisis. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Integer odio leo, aliquam quis molestie sit amet, luctus ut nunc. Donec molestie, turpis at fringilla sodales, magna sem tempus neque, eu tempus dui nisl viverra risus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nam ut mi vel erat adipiscing aliquam eget non tellus. Fusce lectus enim, pulvinar vitae varius id, sodales et turpis. Pellentesque faucibus erat ac ante lacinia id blandit velit consectetur.",

        "Sed quis nisi et eros gravida euismod vitae id leo. Cras eu enim vel sapien volutpat imperdiet. Sed non tortor at arcu hendrerit elementum a vestibulum sapien. Phasellus lectus dolor, malesuada ut cursus sed, convallis in sapien. Suspendisse imperdiet justo et elit iaculis vitae pellentesque enim convallis. Suspendisse potenti. Integer auctor pellentesque diam, in tristique arcu suscipit quis.",

        "Curabitur et urna nec lorem elementum aliquet eu ac elit. Fusce facilisis diam non nibh pulvinar congue. Proin ut lorem a arcu sodales lobortis id quis felis. Donec vel purus vitae eros posuere congue a vitae nibh. Vestibulum malesuada commodo elit. Maecenas viverra, libero sed pellentesque fermentum, mi lacus malesuada ligula, cursus fringilla purus ante quis libero. Etiam accumsan est vitae quam aliquam venenatis. Donec nec mi metus. Curabitur pretium consectetur dolor eget convallis. Aliquam erat volutpat. Curabitur in metus sit amet orci tristique imperdiet eget non ipsum. Aenean sagittis commodo felis, et tincidunt elit semper sit amet. Aliquam nulla leo, posuere sit amet convallis eget, tempor sit amet purus.",

        "Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Aliquam mollis malesuada semper. Suspendisse dolor orci, imperdiet eget semper eu, dictum at nisl. Fusce luctus metus eros. Fusce et felis mi, a mattis sem. Suspendisse neque nunc, dictum sed porttitor eget, hendrerit eget tellus. Proin feugiat mi eget leo vulputate vehicula. Nulla et augue ac lorem rhoncus tincidunt. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Aliquam dapibus viverra risus in vestibulum. Vestibulum tortor massa, gravida ut tincidunt id, fringilla id erat. Proin ante felis, egestas non cursus a, ornare mattis augue. Cras orci risus, commodo et vulputate et, ultricies at odio. Maecenas augue leo, pellentesque vitae condimentum non, posuere tincidunt lectus. Phasellus pulvinar sodales molestie.",

        "Aenean risus sapien, mollis et accumsan at, elementum ut nisl. Vestibulum in ornare nisi. Sed euismod nunc ut felis ullamcorper eleifend. Maecenas mattis luctus eleifend. Nulla id augue eget ante interdum porta. Maecenas varius neque turpis. Donec mattis interdum libero, sit amet aliquam leo ornare eget. Integer tincidunt, odio nec scelerisque dapibus, lacus mi tincidunt mi, vel luctus purus urna id sapien. Sed mi felis, faucibus et fringilla nec, pulvinar ac velit. Vestibulum lobortis justo ultrices lectus tincidunt pellentesque. Nam quis ultrices mi.",

        "Ut vel nulla magna, eget luctus odio. Suspendisse porta auctor facilisis. Donec vestibulum, ante quis dignissim scelerisque, ante ante euismod arcu, non porta lectus tellus eget eros. Phasellus dolor sem, dapibus eget aliquam scelerisque, vulputate vitae ipsum. Aenean et enim dolor, eget condimentum orci. Donec nec varius nisl. Vivamus sagittis tincidunt lacus sit amet eleifend. Vivamus dapibus placerat ullamcorper. Aliquam blandit bibendum eros quis tristique. In sit amet arcu vel sapien laoreet mattis. Morbi faucibus auctor dui eget tincidunt. Nulla facilisi. Quisque placerat lectus ac mi porta vitae rutrum massa tincidunt. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.",

        "Maecenas fringilla, dui eu rhoncus volutpat, nibh nulla rutrum quam, sed pulvinar risus risus et diam. Sed non porta nisi. Curabitur dapibus vestibulum ullamcorper. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Morbi in arcu eu sem vestibulum euismod ut in tellus. Nulla facilisis tristique viverra. Sed nec auctor arcu. Pellentesque id ante ligula. Nunc pellentesque lobortis nisi non semper. Donec sit amet risus non augue sagittis porttitor a vel ligula. Phasellus vel diam magna, scelerisque scelerisque dolor.",

        "Aenean a enim orci. Sed feugiat mauris vel quam sollicitudin ullamcorper. Maecenas aliquet dapibus turpis, eu pellentesque mi euismod at. Curabitur quis dictum ipsum. Maecenas tortor metus, sodales at lobortis et, aliquam non diam. Mauris sed justo at sem auctor semper vehicula nec lacus. Vestibulum rhoncus, leo nec pulvinar interdum, nunc tellus interdum tellus, id rhoncus diam augue sit amet orci. Integer convallis rhoncus lacus, non malesuada est egestas et. Phasellus pulvinar placerat orci at convallis.",

        "Nam sed magna sem, ac dictum sem. Morbi sagittis iaculis magna at lacinia. Mauris elementum vehicula dolor, quis tincidunt sapien cursus a. Ut ultrices, nulla ac feugiat semper, ligula enim rutrum turpis, in tempor turpis enim a turpis. Suspendisse a augue nulla. Nulla commodo ligula sit amet turpis sodales vitae congue orci eleifend. Nullam at enim purus. Vivamus convallis elementum eros ac facilisis. Duis imperdiet turpis consectetur sem rutrum mollis. Integer convallis sem risus, sed consectetur est. Aenean eget nulla at tortor varius feugiat. Phasellus eu nunc eget risus lacinia bibendum eu a est. Donec porttitor euismod sapien eu iaculis. Nullam ut lectus elit.",

        "Nulla vel dui nulla, ut scelerisque tellus. Morbi ipsum quam, rhoncus fringilla rutrum vel, fermentum ac ipsum. Aenean elementum elit sed metus tincidunt aliquet. Phasellus accumsan posuere ipsum, non rutrum enim dictum eget. Praesent posuere imperdiet nisi sodales auctor. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Suspendisse potenti. Aenean ac velit non urna molestie porttitor. Aenean ut risus a augue sagittis varius.",

        "Mauris egestas hendrerit lacus, quis mattis dui tempus a. Mauris rutrum, enim congue fermentum condimentum, elit neque egestas eros, at laoreet nisl nibh vel elit. Nullam eget nunc tellus, ac convallis nunc. Pellentesque in leo in sem semper ullamcorper congue ac nulla. Curabitur vehicula feugiat nunc et viverra. Fusce vitae tortor massa. In vitae quam risus, in viverra felis.",

        "Aliquam lobortis neque lorem. Fusce ipsum urna, viverra vel blandit non, mollis eu odio. Integer ut purus nibh, sed vulputate justo. Sed elit odio, adipiscing placerat faucibus vitae, viverra sed lectus. Ut varius mauris ac diam luctus ornare. Nunc id massa mauris, eu porta nisl. Duis dignissim eros eget augue scelerisque blandit.",

        "Phasellus posuere imperdiet purus. Nam enim urna, luctus at ultrices sed, euismod eget purus. Fusce ornare, erat non porttitor elementum, justo mauris hendrerit arcu, ut gravida diam tellus et risus. Aenean aliquam mauris nec ligula faucibus porttitor. Vivamus elit nisi, accumsan sed porttitor in, dictum ac purus. Praesent a augue sit amet eros ultricies lacinia. Maecenas sit amet diam libero, eu viverra elit. Cras rhoncus hendrerit ligula, nec laoreet ipsum accumsan a. Morbi ac tortor arcu.",

        "Cras sapien velit, porttitor ut scelerisque quis, iaculis eu turpis. Ut scelerisque malesuada euismod. Cras eget dui elit, at tristique dui. Phasellus quis eros lacus, in ultrices massa. Cras varius ligula vel nibh suscipit adipiscing. Maecenas aliquam, sapien sit amet semper ornare, lorem purus tempus neque, vel commodo libero risus quis ligula. Mauris varius rhoncus tincidunt. Mauris pretium est neque. Suspendisse potenti. Sed elit odio, tempor eu sollicitudin at, hendrerit at mauris. Nunc vitae justo vitae quam sagittis ornare ut molestie enim. Pellentesque vehicula bibendum tortor vulputate pharetra.",

        "Integer nibh diam, molestie vel ornare non, adipiscing ac dui. Pellentesque arcu tortor, luctus eget convallis vel, gravida sed urna. Mauris nunc nibh, faucibus vitae porta sed, faucibus non elit. Ut nec purus vel lacus ultricies dapibus. Donec imperdiet ipsum at lorem viverra egestas. Aenean urna sem, bibendum non faucibus quis, congue ut justo. Praesent tempor fringilla augue placerat elementum. Maecenas iaculis felis sed lectus consequat rhoncus. Nam vulputate sagittis orci eu ultrices. Donec sapien enim, semper id luctus at, rutrum dapibus orci. In hac habitasse platea dictumst. Duis vel mollis est.",

        "Nulla facilisi. Sed dictum, lorem sed dictum malesuada, dolor magna congue purus, nec vestibulum tortor massa imperdiet nibh. Suspendisse turpis ligula, semper eu pharetra a, faucibus eu lorem. Vivamus sem velit, ornare ut feugiat et, aliquet et nibh. Etiam blandit erat ut orci auctor faucibus. Etiam quis lectus nunc, ac pretium dolor. Vivamus cursus, lorem quis semper vestibulum, odio lorem vestibulum mauris, nec cursus massa mauris vitae sem. Suspendisse potenti. Ut euismod ante non lacus molestie venenatis. Fusce arcu mi, lacinia non porta eu, semper eu nisi. Curabitur pretium eleifend massa ac egestas. Fusce pellentesque ante sapien, et lacinia mi.",

        "Suspendisse potenti. In hac habitasse platea dictumst. Aenean molestie leo nec lorem fermentum facilisis. Nullam id nibh erat. Proin eu lacus metus. Vestibulum at tellus turpis, eu varius leo. Aliquam a erat sem, ac luctus turpis. Fusce nunc ipsum, tincidunt eget faucibus sit amet, hendrerit ac turpis. Quisque lobortis pretium lectus, non feugiat massa lobortis eu. In tellus tortor, sodales et venenatis eget, hendrerit sed augue. Nam nec nibh sapien. Vestibulum tortor lacus, adipiscing vitae varius in, eleifend non enim. Fusce id metus sem. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut nibh diam, porttitor sed blandit lacinia, mattis a tellus. Nulla facilisi."

    };

}
